In [1]:
import pandas as pd

In [4]:
data =pd.read_excel("customer_data.xlsx")

In [6]:
data.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No

In [13]:
data["Date_of_Purchase"]=data["Date_of_Purchase"].astype("datetime64[ns]")

In [29]:
data["Year"]=data["Date_of_Purchase"].dt.year
data["Month"]=data["Date_of_Purchase"].dt.month
data["Day"]=data["Date_of_Purchase"].dt.day
data=data.drop("Date_of_Purchase",axis=1)

In [30]:
data.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Churn_Status,Year,Month,Day
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,Yes,2022,3,5
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,Yes,2023,7,8
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,No,2023,1,30
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,No,2023,6,1
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,No,2022,9,23