In [3]:
import pandas as pd
from sklearn. preprocessing import LabelEncoder

In [4]:
data = pd.read_excel("customer_data.xlsx")
data.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No

In [7]:
encoder = LabelEncoder()
data["Churn_Status"]=encoder.fit_transform(data["Churn_Status"])
data.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,1
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,1
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,0
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,0
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,0