In [1]:
import pandas as pd

In [2]:
data = pd.read_excel("customer_data.xlsx")

In [3]:
data.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No

In [9]:
dummies = pd.get_dummies(data[["Gender","City","Region","Purchase_Channel"]],dtype=int)
data=pd.concat([data,dummies],axis=1)
data.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,...,Gender_Male,City_Chicago,City_Houston,City_Los Angeles,City_New York,Region_Midwest,Region_Northeast,Region_West,Purchase_Channel_In-store,Purchase_Channel_Online
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,...,1,1,0,0,0,0,1,0,0,1
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,...,0,0,0,0,1,0,0,1,1,0
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,...,1,0,0,0,1,0,1,0,0,1
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,...,1,1,0,0,0,1,0,0,1,0
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,...,1,0,1,0,0,1,0,0,0,1